# Generated by Django 3.0.2 on 2020-01-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
