# Generated by Django 3.0.2 on 2020-01-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_student_semail'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50)),
                ('b_pic', models.ImageField(upload_to='assets/image')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
